# Generated by Django 5.2.17 on 2026-08-27 21:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=150, verbose_name='Nombre del Cliente')),
                ('nombre_evento', models.CharField(max_length=150, verbose_name='Nombre del Evento (ej. Bodas de Ana y Luis)')),
                ('tipo', models.CharField(choices=[('INDIVIDUAL', 'Sesión Individual / Cliente Único'), ('EVENTO_GRANDE', 'Evento Grande (Bodas / XV Años con QR)')], default='INDIVIDUAL', max_length=20)),
                ('pin_acceso', models.CharField(max_length=10, verbose_name='PIN de acceso')),
                ('limite_almacenamiento_mb', models.IntegerField(default=5000, verbose_name='Límite MB')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('dias_vigencia', models.IntegerField(default=30, verbose_name='Días activa')),
                ('activo', models.BooleanField(default=True, verbose_name='Galería Activa')),
            ],
        ),
    ]
