# Generated by Django 5.2.17 on 2026-08-30 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='limite_almacenamiento_mb',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='pin_acceso',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='tipo',
        ),
        migrations.AddField(
            model_name='evento',
            name='plan_almacenamiento',
            field=models.IntegerField(choices=[(5000, 'Básico (5 GB)'), (10000, 'Estándar (10 GB)'), (15000, 'Premium (15 GB)')], default=5000, verbose_name='Plan contratado'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='dias_vigencia',
            field=models.IntegerField(default=30, verbose_name='Días activa para invitados'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='nombre_cliente',
            field=models.CharField(max_length=150, verbose_name='Nombre de los Novios / Festejado'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='nombre_evento',
            field=models.CharField(max_length=150, verbose_name='Nombre del Evento'),
        ),
        migrations.CreateModel(
            name='FotoInvitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.ImageField(upload_to='fotos_eventos/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='galerias.evento')),
            ],
        ),
    ]
