# Generated by Django 5.2.17 on 2026-08-30 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerias', '0002_remove_evento_limite_almacenamiento_mb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='dias_vigencia',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='evento',
            name='nombre_cliente',
            field=models.CharField(max_length=150, verbose_name='Nombre de los Clientes'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='plan_almacenamiento',
            field=models.IntegerField(choices=[(5000, 'Básico (5 GB)'), (10000, 'Estándar (10 GB)'), (15000, 'Premium (15 GB)')], default=5000, verbose_name='Plan'),
        ),
        migrations.AlterField(
            model_name='fotoinvitado',
            name='archivo',
            field=models.FileField(upload_to='archivos_eventos/'),
        ),
        migrations.AlterField(
            model_name='fotoinvitado',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='galerias.evento'),
        ),
    ]
