# Generated by Django 5.2.17 on 2026-08-30 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerias', '0003_alter_evento_activo_alter_evento_dias_vigencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotoinvitado',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='galerias.evento'),
        ),
    ]
