# Generated by Django 5.2.17 on 2026-08-31 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerias', '0004_alter_fotoinvitado_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='tema_color',
            field=models.CharField(choices=[('clasico', 'Clásico / Gris Neumórfico (#e0e5ec)'), ('rosa_pastell', 'Rosa & Pastel (Baby Shower / XV Años)'), ('azul_elegante', 'Azul Noche & Plata (Graduaciones / Bodas)'), ('verde_bosque', 'Verde Bosque & Muted Teal (Botánico / Orgánico)'), ('morado_fiesta', 'Morado & Lavanda (Fiestas / Neón)'), ('blanco_boda', 'Blanco Marfil & Dorado (Bodas Elegantes)')], default='clasico', max_length=30, verbose_name='Paleta de Colores'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='plan_almacenamiento',
            field=models.IntegerField(choices=[(200, 'DEBUG 200MB'), (5000, 'Básico (5 GB)'), (10000, 'Estándar (10 GB)'), (15000, 'Premium (15 GB)')], default=5000, verbose_name='Plan'),
        ),
    ]
