# Generated by Django 5.2.17 on 2026-09-03 06:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerias', '0005_evento_tema_color_alter_evento_plan_almacenamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='pin_dueno',
            field=models.CharField(default='0000', help_text='PIN de 4 dígitos para acceso del dueño', max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'El PIN debe ser exactamente de 4 dígitos numéricos.')]),
        ),
    ]
