# Generated by Django 5.2.17 on 2026-09-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerias', '0006_evento_pin_dueno'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='fondo_personalizado',
            field=models.ImageField(blank=True, null=True, upload_to='fondos_eventos/', verbose_name='Fondo Personalizado'),
        ),
        migrations.AddField(
            model_name='evento',
            name='mensaje_bienvenida',
            field=models.CharField(blank=True, help_text="Mensaje emergente al abrir la galería (ej. '¡Bienvenidos a la boda de Ana y Mario!')", max_length=200, null=True, verbose_name='Mensaje de Bienvenida'),
        ),
        migrations.AddField(
            model_name='evento',
            name='plantilla_html',
            field=models.CharField(choices=[('clasica', 'Estructura Clásica'), ('grid_moderno', 'Grid Moderno'), ('editorial', 'Estilo Editorial')], default='clasica', max_length=30, verbose_name='Plantilla de la Galería'),
        ),
        migrations.AddField(
            model_name='fotoinvitado',
            name='destacada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fotoinvitado',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fotoinvitado',
            name='mensaje',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Mensaje del invitado'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='dias_vigencia',
            field=models.IntegerField(default=20, verbose_name='Días de Vigencia'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='plan_almacenamiento',
            field=models.IntegerField(choices=[(200, 'DEBUG (200 MB)'), (5000, 'Esencial (5 GB - $650 MXN)'), (10000, 'Experiencia (10 GB - $900 MXN)'), (15000, 'Premium (15 GB - $1,500 MXN)')], default=5000, verbose_name='Plan'),
        ),
    ]
