# Generated by Django 5.2.17 on 2026-09-05 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerias', '0007_evento_fondo_personalizado_evento_mensaje_bienvenida_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Marco')),
                ('imagen', models.ImageField(upload_to='marcos_eventos/', verbose_name='Imagen PNG del Marco')),
                ('solo_premium', models.BooleanField(default=False, help_text='Si se marca, solo los eventos con plan Premium podrán elegir este marco.', verbose_name='Exclusivo Premium')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Marco',
                'verbose_name_plural': 'Marcos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='marco_seleccionado',
            field=models.ForeignKey(blank=True, help_text='Marco PNG que se superpondrá sobre las fotos (Disponible en Experiencia y Premium)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='galerias.marco', verbose_name='Marco Personalizado'),
        ),
    ]
