# Generated by Django 5.2.17 on 2026-09-11 07:18

import galerias.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerias', '0008_marco_evento_marco_seleccionado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotoinvitado',
            name='archivo',
        ),
        migrations.AddField(
            model_name='fotoinvitado',
            name='alto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fotoinvitado',
            name='ancho',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fotoinvitado',
            name='estado_procesamiento',
            field=models.CharField(choices=[('PROCESANDO', 'Procesando...'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error')], default='COMPLETADO', max_length=20),
        ),
        migrations.AddField(
            model_name='fotoinvitado',
            name='original_archivo',
            field=models.FileField(default='', upload_to=galerias.models.get_original_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fotoinvitado',
            name='peso_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fotoinvitado',
            name='preview_archivo',
            field=models.FileField(blank=True, null=True, upload_to=galerias.models.get_preview_path),
        ),
        migrations.AddField(
            model_name='fotoinvitado',
            name='thumb_archivo',
            field=models.FileField(blank=True, null=True, upload_to=galerias.models.get_thumb_path),
        ),
        migrations.AddField(
            model_name='fotoinvitado',
            name='tipo',
            field=models.CharField(choices=[('IMAGEN', 'Imagen'), ('VIDEO', 'Video')], default='IMAGEN', max_length=10),
        ),
    ]
