# Generated by Django 5.2.17 on 2026-09-12 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerias', '0009_remove_fotoinvitado_archivo_fotoinvitado_alto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_solicitante', models.CharField(max_length=150, verbose_name='Nombre del Solicitante')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('nombre_evento', models.CharField(max_length=150, verbose_name='Nombre del Evento')),
                ('nombre_cliente', models.CharField(max_length=150, verbose_name='Nombre de los Clientes')),
                ('plan_almacenamiento', models.IntegerField(choices=[(200, 'DEBUG (200 MB)'), (5000, 'Esencial (5 GB - $650 MXN)'), (10000, 'Experiencia (10 GB - $900 MXN)'), (15000, 'Premium (15 GB - $1,500 MXN)')], default=5000, verbose_name='Plan')),
                ('plantilla_html', models.CharField(choices=[('clasica', 'Estructura Clásica'), ('grid_moderno', 'Grid Moderno'), ('editorial', 'Estilo Editorial')], default='clasica', max_length=30, verbose_name='Plantilla de la Galería')),
                ('tema_color', models.CharField(choices=[('clasico', 'Clásico / Gris Neumórfico (#e0e5ec)'), ('rosa_pastell', 'Rosa & Pastel (Baby Shower / XV Años)'), ('azul_elegante', 'Azul Noche & Plata (Graduaciones / Bodas)'), ('verde_bosque', 'Verde Bosque & Muted Teal (Botánico / Orgánico)'), ('morado_fiesta', 'Morado & Lavanda (Fiestas / Neón)'), ('blanco_boda', 'Blanco Marfil & Dorado (Bodas Elegantes)')], default='clasico', max_length=30, verbose_name='Paleta de Colores')),
                ('fondo_personalizado', models.ImageField(blank=True, null=True, upload_to='fondos_solicitudes/', verbose_name='Fondo Personalizado')),
                ('mensaje_bienvenida', models.CharField(blank=True, help_text="Mensaje emergente al abrir la galería (ej. '¡Bienvenidos a la boda de Ana y Mario!')", max_length=200, null=True, verbose_name='Mensaje de Bienvenida')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('notas_admin', models.TextField(blank=True, null=True, verbose_name='Notas del Admin')),
                ('evento_creado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitud_origen', to='galerias.evento', verbose_name='Evento Creado')),
                ('marco_seleccionado', models.ForeignKey(blank=True, help_text='Marco PNG que se superpondrá sobre las fotos (Disponible en Experiencia y Premium)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='galerias.marco', verbose_name='Marco Personalizado')),
            ],
            options={
                'verbose_name': 'Solicitud de Evento',
                'verbose_name_plural': 'Solicitudes de Eventos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
