# Generated by Django 5.2.17 on 2026-09-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerias', '0010_solicitudevento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='descargas_zip_restantes',
            field=models.IntegerField(default=3, help_text='Número de descargas completas permitidas al dueño', verbose_name='Descargas ZIP restantes'),
        ),
        migrations.AddField(
            model_name='evento',
            name='duracion_total_horas',
            field=models.IntegerField(default=24, help_text='24 horas base + horas extra contratadas', verbose_name='Duración total en horas'),
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha_hora_inicio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de inicio del evento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='horas_extra',
            field=models.IntegerField(default=0, help_text='Cada bloque de 24 horas extra cuesta $100 MXN', verbose_name='Horas extra (bloques de 24h)'),
        ),
        migrations.AddField(
            model_name='solicitudevento',
            name='fecha_hora_inicio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de inicio del evento'),
        ),
        migrations.AddField(
            model_name='solicitudevento',
            name='horas_extra',
            field=models.IntegerField(default=0, help_text='Cada bloque de 24 horas extra cuesta $100 MXN', verbose_name='Horas extra (bloques de 24h)'),
        ),
    ]
