# Generated by Django 5.2.17 on 2026-09-12 21:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerias', '0011_evento_descargas_zip_restantes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudevento',
            name='telefono',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'El teléfono debe contener solo números.')], verbose_name='Teléfono'),
        ),
    ]
