# Generated by Django 5.2.17 on 2026-09-12 21:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerias', '0012_alter_solicitudevento_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudevento',
            name='telefono',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9]{10}$', 'El teléfono debe tener exactamente 10 dígitos.')], verbose_name='Teléfono'),
        ),
    ]
