# Generated by Django 5.2.17 on 2026-09-12 21:38

import galerias.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerias', '0013_alter_solicitudevento_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fondo_personalizado',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='fondos_eventos/', verbose_name='Fondo Personalizado'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='plan_almacenamiento',
            field=models.IntegerField(choices=[(200, 'DEBUG (200 MB)'), (5000, 'Esencial (5 GB - $500 MXN)'), (10000, 'Experiencia (10 GB - $900 MXN)'), (15000, 'Premium (15 GB - $1,500 MXN)')], default=5000, verbose_name='Plan'),
        ),
        migrations.AlterField(
            model_name='fotoinvitado',
            name='original_archivo',
            field=models.FileField(max_length=500, upload_to=galerias.models.get_original_path),
        ),
        migrations.AlterField(
            model_name='fotoinvitado',
            name='preview_archivo',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=galerias.models.get_preview_path),
        ),
        migrations.AlterField(
            model_name='fotoinvitado',
            name='thumb_archivo',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=galerias.models.get_thumb_path),
        ),
        migrations.AlterField(
            model_name='marco',
            name='imagen',
            field=models.ImageField(max_length=500, upload_to='marcos_eventos/', verbose_name='Imagen PNG del Marco'),
        ),
        migrations.AlterField(
            model_name='solicitudevento',
            name='fondo_personalizado',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='fondos_solicitudes/', verbose_name='Fondo Personalizado'),
        ),
        migrations.AlterField(
            model_name='solicitudevento',
            name='plan_almacenamiento',
            field=models.IntegerField(choices=[(200, 'DEBUG (200 MB)'), (5000, 'Esencial (5 GB - $500 MXN)'), (10000, 'Experiencia (10 GB - $900 MXN)'), (15000, 'Premium (15 GB - $1,500 MXN)')], default=5000, verbose_name='Plan'),
        ),
    ]
