# Generated by Django 5.2.17 on 2026-09-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerias', '0014_alter_evento_fondo_personalizado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='tema_color',
            field=models.CharField(choices=[('clasico', 'Clásico / Gris Neumórfico'), ('rosa_pastell', 'Rosa & Pastel'), ('azul_elegante', 'Azul Noche & Plata'), ('verde_bosque', 'Verde Bosque & Muted Teal'), ('morado_fiesta', 'Morado & Lavanda'), ('blanco_boda', 'Blanco Marfil & Dorado')], default='clasico', max_length=30, verbose_name='Paleta de Colores'),
        ),
        migrations.AlterField(
            model_name='solicitudevento',
            name='tema_color',
            field=models.CharField(choices=[('clasico', 'Clásico / Gris Neumórfico'), ('rosa_pastell', 'Rosa & Pastel'), ('azul_elegante', 'Azul Noche & Plata'), ('verde_bosque', 'Verde Bosque & Muted Teal'), ('morado_fiesta', 'Morado & Lavanda'), ('blanco_boda', 'Blanco Marfil & Dorado')], default='clasico', max_length=30, verbose_name='Paleta de Colores'),
        ),
    ]
