# Generated by Django 5.2.17 on 2026-09-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerias', '0015_alter_evento_tema_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='plan_almacenamiento',
            field=models.IntegerField(choices=[(5000, 'Esencial (5 GB - $500 MXN)'), (10000, 'Experiencia (10 GB - $900 MXN)'), (15000, 'Premium (15 GB - $1,500 MXN)')], default=5000, verbose_name='Plan'),
        ),
        migrations.AlterField(
            model_name='solicitudevento',
            name='plan_almacenamiento',
            field=models.IntegerField(choices=[(5000, 'Esencial (5 GB - $500 MXN)'), (10000, 'Experiencia (10 GB - $900 MXN)'), (15000, 'Premium (15 GB - $1,500 MXN)')], default=5000, verbose_name='Plan'),
        ),
    ]
